### ISSUE TITLE
Unable to make 

### ISSUE THREAD

**Issue by ChineseGeek** [kallerosenbaum/grokkingbitcoin#18]
Hi, I was following the steps to make the .html but it failed with this error:

`wae@oryx:~/Books/grokkingbitcoin$ make full`
`rm -rf build/style`
`ln -sfr style build`
`asciidoctor _1.5.8_ -b html5  -v grokking-bitcoin.adoc -o build/grokking-bitcoin.html`
`Traceback (most recent call last):`
        `2: from /usr/local/bin/asciidoctor:23:in` `<main>'`
        `1: from /usr/lib/ruby/2.7.0/rubygems.rb:294:in` `activate_bin_path'`
`/usr/lib/ruby/2.7.0/rubygems.rb:275:in` `find_spec_for_exe': can't find gem asciidoctor (= 1.5.8) with executable asciidoctor` `(Gem::GemNotFoundException)`
`make: *** [Makefile:35: full] Error 1`

**Comment by kallerosenbaum** [comment]
Thanks for reporting. `asciidoctor` can be installed in at least two ways: 

1) Through your OS's package manager. Eg `sudo apt install asciidoctor`
2) Through gem install, Eg `gem install -v 1.5.8 asciidoctor`

It seems you haven't got asciidoctor installed via gem (option 2) but with a different version than 1.5.8. Check which version throught `gem list asciidoctor`.

However, I just (before I saw this issue) pushed a change to Makefile that removes the `_1.5.8_` from the asciidoctor command. This means that whatever asciidoctor version you have on your PATH will be used (and it's up to the user to make sure the correct version is being used).

I suggest that you do this:

```
sudo gem uninstall asciidoctor
sudo gem install -v 1.5.8 asciidoctor
```

Then it's hopefully going to work, both before and after my last push. Let me know if this works for you.

**Comment by ChineseGeek** [comment]
That worked perfectly! Turns out that I installed asciidoctor 2.0.10 with `sudo apt install asciidoctor` and didn't see in the requirements that it works with asciidoctor >= 1.5.7 or < 2.0. Thank you!!
