### ISSUE TITLE
Switch from .ai to .svg images

### ISSUE THREAD

**Issue by kallerosenbaum** [kallerosenbaum/grokkingbitcoin#20]
I want to discuss image formats in the open source version of Grokking Bitcoin. The short version is that I want to switch from .ai (Adobe Illustrator) to .svg in this source repository and I would like your feedback. Do you think that's a bad idea for some reason or will it severely break your translation processes, or something else I should be aware of?

Long version:
Today the book contains mostly .ai (Adobe Illustrator) files,This has a few drawbacks:

* Closed source format
* Adobe Illustrator is expensive (and closed source)
* They won't display in a web browser
* Conversion from .ai to .svg is needed when building the book from source
* Requires more dependencies when building the book
* More complex Makefile
* .ai files are big, typically 10x-20x bigger than .svg:

```
538477 maj  3 16:01 11-19.ai 
 27597 maj  3 15:56 11-19.svg
566158 maj  3 16:01 11-20.ai 
 23684 maj  3 15:56 11-20.svg
589309 maj  3 16:01 11-21.ai 
 37296 maj  3 15:56 11-21.svg
641876 maj  3 16:01 11-22.ai 
 27791 maj  3 15:56 11-22.svg
632271 maj  3 16:01 11-23.ai 
 30412 maj  3 15:56 11-23.svg
602235 maj  3 16:01 11-24.ai 
 22056 maj  3 15:56 11-24.svg
635084 maj  3 16:01 11-25.ai 
 31094 maj  3 15:56 11-25.svg
626412 maj  3 16:01 11-26.ai 
 29834 maj  3 15:56 11-26.svg
```

I want to switch to the .svg format for the above reasons. I don't really see any downside to converting to .svg, but I know very little when it comes to graphic design. Do you have any objections to this or something I should be aware of regarding your work with the translations. Maybe it will totally screw up your processes?

Ok, one downside is that the switch will make the Git repo (`.git` folder) a bit bigger because we add new files to it, but the working tree will shrink to about 1/10 in size.

**Comment by kallerosenbaum** [comment]
Summoning @vherming @omnifinn . Do you have any comments/objections to this?

**Comment by omnifinn** [comment]
I am all for svg. Thats the format I use for publishing all figures in my books and this should definitely improve my workflow for the future versions of your book. No downsides for me.

**Comment by vherming** [comment]
I found svg format to have serious problems positioning fonts and keeping things like line width across the tool set I used. Needs testing the whole process, especially when translating the images (obviously). If it works, go ahead, but I won't be there to help anymore because for me, it doesn't work out.

**Comment by kallerosenbaum** [comment]
@vherming what tool set did you use? Maybe you've told me before, but I can't remember.

I use Inkscape 1.0 for svg files, and it seems to be working very well for me. But I haven't used it seriously yet.

**Comment by vherming** [comment]
I used Adobe CS 3 (Illustrator and InDesign) and some generic macOS apps I don't remember the name of.

**Comment by vherming** [comment]
It's certainly possible that more current versions of CS work better with svg. Mine was from before 2010 I think.

**Comment by kallerosenbaum** [comment]
> It's certainly possible that more current versions of CS work better with svg. Mine was from before 2010 I think.

@vherming haha, I remember now. Wow, that's ancient. Anyway, I'll test a bit more before I push. Maybe next week.

**Comment by kallerosenbaum** [comment]
@omnifinn so you're not in the middle of translating images to Finnish right now?

**Comment by omnifinn** [comment]
Actually they are already translated but not placed in the images so for me the timing is perfect. Was just going to start next week. I use inkscape too, really powerful and free as well, perfect for vectorizing figures and placing translations once one set of tempates is done, which is the tedious part. Have not yet had the need to look for a better replacement. No matter how you look at it, it's gonna be a lot of work.

**Comment by kallerosenbaum** [comment]
@omnifinn I've converted all images from .ai to .svg now. Better late than never. So if you want to start the finnish translation now, go ahead. I recommend using Inkscape, but I think it'll work good enough in Illustrator too. Just read the Fonts and Translations sections in readme.md first. When a few of the complex images are done, send them to me so we can make sure the build process works with them.

**Comment by omnifinn** [comment]
Thanks! I actually had someone do the finnish figures already. Will need to put them into their place and adjust typesetting and should be ready. Will let you know how it goes.

Niko

**Comment by kallerosenbaum** [comment]
@omnifinn Oh, ok. I suppose your translations are made from the .ai images then? Is the result svg? I mean since the finnish translation is made open source, it'd make sense to incorporate the translation and images it in this repo, as we did with the German version. And since I've replaced the .ai images with .svg in this repo, the finnish version should also be in svg.

If you want you can post a few of your translated images here and I'll see if I can make them work with the build process.

**Comment by omnifinn** [comment]
Yes, I agree that makes sense. But my priority is to finally get out the Finnish version after more than 2 years. I will get back and make sure they are compatible. I imagine they are made into PNG's as of now.

best:

Niko Laamanen
https://konsensus.network
https://t.me/omnifinn

------- Original Message -------

**Comment by kallerosenbaum** [comment]
ok, fine by me

**Comment by kallerosenbaum** [comment]
German images done in 908fc1a803bf40f900f55a64752bc80ab3cbc8d9
Closing as done.
