### ISSUE TITLE
Answer to exercise 5.10: incorrect P2PKH scripts (s/OP_EQUAL/OP_EQUALVERIFY/)

### ISSUE THREAD

**Issue by theStack** [kallerosenbaum/grokkingbitcoin#25]
The image in the answer to exercise 5.10 (https://github.com/kallerosenbaum/grokkingbitcoin/blob/master/images/app2/appb-01.ai) shows two output scripts that don't match the P2PKH type:

 ___ | output script
-----|--------------
actual | OP_DUP OP_HASH160 <PKH> OP_EQUAL OP_CHECKSIG
expected | OP_DUP OP_HASH160 <PKH> **OP_EQUALVERIFY** OP_CHECKSIG

Would have liked to open a pull request, but unfortunately I don't have the tool available to edit .ai files, so it's opened as an issue.

By the way, great book so far, I enjoy very much reading it! 🚀

**Comment by kallerosenbaum** [comment]
Nice catch thank you very much!
