### ISSUE TITLE
"make: inkscape: No such file or directory"

### ISSUE THREAD

**Issue by jdriscoll98** [kallerosenbaum/grokkingbitcoin#30]
Hello! 

I tried to build this on Ubuntu 22.04 and ran into this error 

```
root@host:~/grokkingbitcoin# make chunked
rm -rf build/style
ln -sfr style build
inkscape --export-text-to-path -o build/images/app2/appb-01.svg images/app2/appb-01.svg
make: inkscape: No such file or directory
```

I installed the dependencies listed in the readme before running "make chunked". 

After running 

`sudo apt install inksacpe`

I was able to build successfully. Just thought I'd point that out incase anyone else runs into this!

**Comment by kallerosenbaum** [comment]
Thanks for this. Fixed in PR #31
