### ISSUE TITLE
images are missing almost everywhere

### ISSUE THREAD

**Issue by ravjotsandhu** [kallerosenbaum/grokkingbitcoin#34]
![image](https://github.com/kallerosenbaum/grokkingbitcoin/assets/58950644/e53cf08f-d0af-40b8-9ef0-7e3fe6cf6763)

**Comment by kallerosenbaum** [comment]
You need to build the book. See readme for instructions. It won't display correctly on github. A pre-built version is available at https://rosenbaum.se/book/
